disabled_rules: 
  - trailing_whitespace
opt_in_rules: 
  
included: 
  
excluded: 
  - Pods
analyzer_rules: 

# personalised rules
switch_case_alignment:
  indented_cases: true

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown)